projetoRazor/petsSharp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace petsSharp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

projetoRazor/petsSharp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;
using System.Runtime.Intrinsics.Arm;

namespace petsSharp.Pages
{
    public class IndexModel : PageModel
    {
        [BindProperty]
        public string Username { get; set; }
        [BindProperty]
        public string Senha { get; set; }

        public bool mensagemLogin = false;

        public IndexModel()
        {
           
        }

        public void OnGet()
        {
           
        }
        public IActionResult OnPost() {
            if (Username == "admin" && Senha == "12345") {
                return RedirectToPage("/dashboard");
            }
            mensagemLogin = true;
            return Page();
            
        }
    }
}

projetoRazor/petsSharp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace petsSharp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

projetoRazor/petsSharp/Pages/cadastrarFornecedor.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;
using System.Numerics;

namespace petsSharp.Pages
{
    public class cadastrarFornecedorModel : PageModel
    {
        [BindProperty]
        public string Nome { get; set; }
        [BindProperty]
        public string Categoria { get; set; }
        [BindProperty]
        public string Endereco { get; set; }
        [BindProperty]
        public string Bairro { get; set; }
        [BindProperty]
        public string Cidade { get; set; }
        [BindProperty]
        public string Estado { get; set; }
        [BindProperty]
        public string CNPJ { get; set; }
        [BindProperty]
        public string Contato { get; set; }
        public void OnGet()
        {
        }
        public IActionResult OnPost()
        {
            BancoDeDados bancoDeDados = new BancoDeDados();
            SqlDataReader leitor;

            int codigo_fornecedor;

            bancoDeDados.abrirConexao();

            leitor = bancoDeDados.executarQuery("select count(distinct codigo_fornecedor) from tb_fornecedor");
            if (leitor.HasRows)
            {
                leitor.Read();
                codigo_fornecedor = leitor.GetInt32(0) + 1;
            }
            else
            {
                codigo_fornecedor = 1;
            }

            bancoDeDados.fechar();

            string query = $"insert into tb_fornecedor (codigo_fornecedor, nome, categoria, endereco, bairro, cidade, estado, cnpj, contato) values " +
                $"({codigo_fornecedor}, '{Nome}', '{Categoria}', '{Endereco}', '{Bairro}', '{Cidade}', '{Estado}', '{CNPJ}', '{Contato}')";

            bancoDeDados.manipularDado(query);
            return RedirectToPage("/dashboard");
        }
    }
}

projetoRazor/petsSharp/Pages/cadastrarProduto.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace petsSharp.Pages
{
    public class cadastrarProdutoModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

projetoRazor/petsSharp/Pages/dashboard.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;

namespace petsSharp.Pages
{
    public class dashboardModel : PageModel
    {
        [BindProperty]
        //public string nome { get; set; }
        public SqlDataReader leitor { get; set; }
        public int totalVenda { get; set; }
        public int totalProdutosCadastrados { get; set; }

        public int totalServicos { get; set; }
        public int totalServicosPendentes { get; set; }
        public int totalFornecedores { get; set; }
        public decimal valorTotal { get; set; }
        public List<string> ListaFornecedores { get; set; }
        public List<int> valorFornecedores { get; set; }
        public dashboardModel()
        {
            
        }

        public void OnGet()
        {
           BancoDeDados bancoDeDados = new BancoDeDados();

            bancoDeDados.abrirConexao();

            leitor = bancoDeDados.executarQuery("select count(distinct codigo_venda) from tb_venda");
            if (leitor.HasRows)
            {
                leitor.Read();
                totalVenda = leitor.GetInt32(0);
            }
            else
            {
                totalVenda = 0;
            }

            bancoDeDados.fechar();
            bancoDeDados.abrirConexao();

            leitor = bancoDeDados.executarQuery("select count(distinct codigo_produto) from tb_produto");

            if (leitor.HasRows)
            {
                leitor.Read();
                totalProdutosCadastrados = leitor.GetInt32(0);
            }
            else
            {
                totalProdutosCadastrados = 0;
            }

            bancoDeDados.fechar();
            bancoDeDados.abrirConexao();

            leitor = bancoDeDados.executarQuery("select count(distinct codigo_servico) from tb_servicos");

            if (leitor.HasRows)
            {
                leitor.Read();
                totalServicos = leitor.GetInt32(0);
            }
            else
            {
                totalServicos = 0;
            }

            bancoDeDados.fechar();
            bancoDeDados.abrirConexao();

            leitor = bancoDeDados.executarQuery("select count( status_servico) from tb_servicos where status_servico = 'nao'");

            if (leitor.HasRows)
            {
                leitor.Read();
                totalServicosPendentes = leitor.GetInt32(0);
            }
            else
            {
                totalServicosPendentes = 0;
            }

            bancoDeDados.fechar();

            bancoDeDados.abrirConexao();

            leitor = bancoDeDados.executarQuery("select count(distinct codigo_fornecedor) from tb_fornecedor");

            if (leitor.HasRows)
            {
                leitor.Read();
                totalFornecedores = leitor.GetInt32(0);
            }
            else
            {
                totalFornecedores = 0;
            }

            bancoDeDados.fechar();

            bancoDeDados.abrirConexao();

            leitor = bancoDeDados.executarQuery("select sum(valor) from tb_produto");

            if (leitor.HasRows)
            {
                leitor.Read();
                valorTotal = leitor.GetDecimal(0);
            }
            else
            {
                valorTotal = 0;
            }

            bancoDeDados.fechar();

            ListaFornecedores = new List<string>();
            valorFornecedores = new List<int>();

            bancoDeDados.abrirConexao();
            leitor = bancoDeDados.executarQuery("select nome, codigo_fornecedor from tb_fornecedor");
            List<int> codigos = new List<int>();
            while (leitor.HasRows)
            {
                leitor.Read();
                try
                {
                    ListaFornecedores.Add(leitor.GetString(0));
                    codigos.Add(leitor.GetInt32(1));
                }
                catch { break; }
            }
            bancoDeDados.fechar();
            foreach(int codigo in codigos)
            {
                bancoDeDados.abrirConexao();

                leitor = bancoDeDados.executarQuery($"select count(*) from tb_produto where codigo_fornecedor = {codigo}");
                
                
                leitor.Read();
                try
                {
                    valorFornecedores.Add(leitor.GetInt32(0));
                    bancoDeDados.fechar();

                }
                catch { bancoDeDados.fechar();  }
                
            }
            
        }
        public void OnPost() { }

        public void OnPostTeste()
        {
            
        }
    }
}

projetoRazor/petsSharp/Pages/estoque.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;
using System.Drawing;
using System.Reflection;

namespace petsSharp.Pages
{
    public class estoqueModel : PageModel
    {
        [BindProperty]
        public List<Dictionary<string, string>> list_produtos { get; set; }
        [BindProperty]
        public string pesquisa { get; set; }
        [BindProperty]
        public decimal valorTotal { get; set; }
        public estoqueModel() {
            
        }

        public void generateListProdutos()
        {
            valorTotal = 0;
            list_produtos = new List<Dictionary<string, string>>();


            BancoDeDados bancoDeDados = new BancoDeDados();
            SqlDataReader leitor;
            int totalProdutos = 0;



            bancoDeDados.abrirConexao();

            leitor = bancoDeDados.executarQuery("select count(distinct codigo_produto) from tb_produto");
            if (leitor.HasRows)
            {
                leitor.Read();
                totalProdutos = leitor.GetInt32(0) + 1;
            }

            bancoDeDados.fechar();

            bancoDeDados.abrirConexao();

            leitor = bancoDeDados.executarQuery("select * from tb_produto");
            int count = 1;
            while (leitor.HasRows)
            {
                if (count != totalProdutos)
                {
                    Dictionary<string, string> temp_dict = new Dictionary<string, string>();

                    leitor.Read();
                    string nome = leitor.GetString(1);
                    decimal valor = leitor.GetDecimal(2);
                    string categoria = leitor.GetString(3);

                    temp_dict.Add("nome", nome);
                    temp_dict.Add("valor", valor.ToString());
                    valorTotal += valor;
                    temp_dict.Add("categoria", categoria);

                    list_produtos.Add(temp_dict);
                    count++;
                }
                else
                {
                    break;
                }
            }


            bancoDeDados.fechar();
            
        }
        public void OnGet()
        {
            generateListProdutos();
        }

        public void OnPostPesquisa() {
            generateListProdutos();
            if (pesquisa  != null)
            {
                valorTotal = 0;
                pesquisa = pesquisa.Trim().ToLower();
                List<Dictionary<string, string>> temp_list_produtos = new List<Dictionary<string, string>>();
                foreach (Dictionary<string, string> dicionario in list_produtos)
                {
                    if (dicionario["nome"].Contains(pesquisa, StringComparison.OrdinalIgnoreCase) ||
                        dicionario["categoria"].Contains(pesquisa, StringComparison.OrdinalIgnoreCase) ||
                        dicionario["valor"].Contains(pesquisa, StringComparison.OrdinalIgnoreCase))
                    {
                        temp_list_produtos.Add(dicionario);
                        valorTotal += decimal.Parse(dicionario["valor"]);
                    }
                }

                list_produtos = temp_list_produtos;
            }
        }
    }
}

projetoRazor/petsSharp/Pages/gerarNota.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace petsSharp.Pages
{
    public class gerarNotaModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

projetoRazor/petsSharp/Pages/indexAnimais.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;

namespace petsSharp.Pages
{
    public class indexAnimaisModel : PageModel
    {
        [BindProperty]
        public List<Dictionary<string, string>> list_animais { get; set; }

        [BindProperty]
        public string pesquisa { get; set; }
        public void generateListAnimais()
        {
            list_animais = new List<Dictionary<string, string>>();

            BancoDeDados bancoDeDados = new BancoDeDados();
            SqlDataReader leitor;
            int totalAnimais = 0;



            bancoDeDados.abrirConexao();

            leitor = bancoDeDados.executarQuery("select count(distinct codigo_animal) from tb_animal");
            if (leitor.HasRows)
            {
                leitor.Read();
                totalAnimais = leitor.GetInt32(0) + 1;
            }

            bancoDeDados.fechar();

            bancoDeDados.abrirConexao();

            leitor = bancoDeDados.executarQuery("select * from tb_animal");
            int count = 1;
            while (leitor.HasRows)
            {
                if (count != totalAnimais)
                {
                    Dictionary<string, string> temp_dict = new Dictionary<string, string>();

                    leitor.Read();
                    int codigo = leitor.GetInt32(0);
                    string especie = leitor.GetString(1);
                    decimal valor = leitor.GetDecimal(2);                         
                    string descricao = leitor.GetString(4);

                    temp_dict.Add("codigo", codigo.ToString());
                    temp_dict.Add("valor", valor.ToString());
                    temp_dict.Add("especie", especie);
                    temp_dict.Add("descricao", descricao);
                    list_animais.Add(temp_dict);
                    count++;
                }
                else
                {
                    break;
                }
            }


            bancoDeDados.fechar();

        }

        public void OnGet()
        {
            generateListAnimais();
        }

        public void OnPostPesquisa()
        {
            generateListAnimais();
            if (pesquisa != null)
            {
                pesquisa = pesquisa.Trim().ToLower();
                List<Dictionary<string, string>> temp_list_animais = new List<Dictionary<string, string>>();
                foreach (Dictionary<string, string> dicionario in list_animais)
                {
                    if (dicionario["codigo"].Contains(pesquisa, StringComparison.OrdinalIgnoreCase) ||
                        dicionario["valor"].Contains(pesquisa, StringComparison.OrdinalIgnoreCase) ||
                        dicionario["especie"].Contains(pesquisa, StringComparison.OrdinalIgnoreCase) ||
                        dicionario["descricao"].Contains(pesquisa, StringComparison.OrdinalIgnoreCase))
                    {
                        temp_list_animais.Add(dicionario);
                    }
                }

                list_animais = temp_list_animais;
            }
        }

    }
}

projetoRazor/petsSharp/Pages/marcarBanhoEtosa.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;
using System.Drawing;

namespace petsSharp.Pages
{
    public class marcarBanhoEtosaModel : PageModel
    {
		
		[BindProperty]
        public string NomeCliente { get; set; }
		[BindProperty]
        public string NomePET { get; set; }
		[BindProperty]
        public string cpf_cliente { get; set; }
		[BindProperty]
        public string porte {  get; set; }

		[BindProperty]
        public string status { get; set; }
		
		public IActionResult OnPost()
		{
			BancoDeDados bancoDeDados = new BancoDeDados();
			SqlDataReader leitor;
			
			int codigo_servico;

			bancoDeDados.abrirConexao();

			leitor = bancoDeDados.executarQuery("select count(distinct codigo_servico) from tb_servicos");
			if (leitor.HasRows)
			{
				leitor.Read();
				codigo_servico = leitor.GetInt32(0) + 1;
			}
			else
			{
				codigo_servico = 1;
			}

			bancoDeDados.fechar();

			string query = $"insert into tb_servicos (codigo_servico, nome_cliente, status_servico, nome_pet, cpf, porte) values " +
				$"({codigo_servico}, '{NomeCliente}', '{status}', '{NomePET}', '{cpf_cliente}', '{porte}')";

			bancoDeDados.manipularDado(query);
			return RedirectToPage("/dashboard");
		}
	}
}

projetoRazor/petsSharp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Pagina login";
    Layout = null;
}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login</title>
    <link rel="stylesheet" href="~/css/pagina-login.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body style="background-color: #151A30;">
    <header>
    </header>
    <main>
    <form method="post">
        <div class="quadradocentral">
            <p class="textoPetsharp">PETSHARP</p>
            <p class="textoUsuario">Usuário:</p>
            <div class="usuario">
                <input asp-for="@Model.Username" type="text"  class="form-control" id="floatingInput" style="background-color: #151A30; border-color:#151A30; color:white">
                <label for="floatingInput"></label>
              </div>
              <p class="textoSenha">Senha:</p>
              <div class="senha">
                <input asp-for="@Model.Senha" type="password" class="form-control" id="floatingPassword" style="background-color: #151A30; border-color:#151A30; color:white;">
                <label for="floatingPassword"></label>
                    <div class="entrar">
                    <button class="btn btn-success">Entrar</button>
                        
                </div>
                    @if (Model.mensagemLogin)
                    {
                          <h5 class="text-center text-danger">O usuario ou senha foram informados errados</h5>
                    }
              </div>
      
        </div>
        
    </form>
        
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

projetoRazor/petsSharp/Pages/estoque.cshtml
@page
@model petsSharp.Pages.estoqueModel
@{
	Layout = null;

}


<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Estoque</title>
	<link rel="stylesheet" href="~/css/style-estoque.css">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.css">
	<script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.6.2.js"></script>
	<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>

</head>
<body style="background-color: #151A30;">
	<header>
		<div id="cabecalho">
			<img id="profileicon" src="~/img/imagens/profileicon.png">
			<a asp-area="" asp-page="/Index" style="color: red;">Sair</a>
		</div>
	</header>
	<main>
		<div id="menu">
			<a class="textoDashboard" asp-page="/dashboard" asp-area="" style="color: white;">Dashboard</a>
			<img class="dashboard" src="~/img/tela-principal/dashboard.png">
			<div class="selecionado">
				<a class="textoEstoque" asp-page="/estoque" asp-area="" style="color: #004BE3">Estoque</a>
				<img class="estoque" src="~/img/tela-principal/estoque.png">
				<a class="textoCadastrarProduto" asp-page="/addProduto" asp-area="" style="color: white;">Cadastrar produto</a>
				<a class="textoCadastrarFornecedor" asp-page="/cadastrarFornecedor" asp-area="" style="color: white;">Cadastrar fornecedor</a>
			</div>
			<a class="textoVendas" asp-page="/indexVendas" asp-area="" style="color: white;">Vendas</a>
			<img class="vendas" src="~/img/tela-principal/sales.png">
			<a class="textoAnimais" asp-page="/indexAnimais" asp-area="" style="color: white;">Animais</a>
			<img class="animais" src="~/img/tela-principal/animais.png">
			<a class="textoBanhoetosa" asp-page="/indexBanhoETosa" asp-area="" style="color: white;">Banho e tosa</a>
			<img class="tesoura" src="~/img/tela-principal/tesoura.png">
		</div>
		<div class="quadradoCentral">
			<form asp-page-handler="Pesquisa" method="post" class="d-flex barraDePesquisa" role="search">
				<input asp-for="@Model.pesquisa" class="form-control text-white border-black" type="search" placeholder="" aria-label="Search" style="background-color: #212B46; width: 200px;">
				<button class="btn border-black" type="submit" style="background-color: #212B46; color: white;">Pesquisar</button>
			</form>

			<div class="container mt-4">
				<div class="table-responsive">
					<table class="table table-striped table-dark dataTable" id="tabelaProdutos">
						<thead>
							<tr>
								<th scope="col">Nome</th>
								<th scope="col">Categoria</th>
								<th scope="col">Valor Unitário</th>
							</tr>
						</thead>
						<tbody>
							@foreach (Dictionary<string, string> dicionario in Model.list_produtos)
							{
								<tr>
									<td>@dicionario["nome"]</td>
									<td>@dicionario["categoria"]</td>
									<td>R$ @dicionario["valor"]</td>
								</tr>
							}

							<tr>
								<td class="font-weight-bold"></td>
								<td class="font-weight-bold"><b>Valor Total:</b></td>
								<td class="font-weight-bold">
									<b>R$ @Model.valorTotal</b>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>

		</div>
	</main>
	<script>
		$(document).ready(function () {
			$('#tabelaProdutos').DataTable({
				"paging": true,
				"pageLength": 10,
				"lengthMenu": [10, 20, 50],
				"info": false,
				"searching": false,
				"language": {
					"emptyTable": "Sem dados disponíveis",
					"info": "Mostrando _START_ até _END_ de _TOTAL_ registros",
					"infoEmpty": "Mostrando 0 até 0 de 0 registros",
					"infoFiltered": "(filtrado de _MAX_ registros no total)",
					"lengthMenu": "Mostrar _MENU_ registros por página",
					"zeroRecords": "Nenhum registro encontrado",
					"paginate": {
						"first": "Primeiro",
						"previous": "Anterior",
						"next": "Próximo",
						"last": "Último"
					}
				},
				"drawCallback": function (settings) {
					$('.custom-length-text').css('color', 'white');
					$('.custom-paginate-text').find('label').css('color', 'white');
				}

			});

			$('.dataTables_length').find('label').css('color', 'white');
			$('.dataTables_paginate').find('label').css('color', 'white !important');

		});
	</script>
</body>
</html>

projetoRazor/petsSharp/Pages/indexAnimais.cshtml
@page
@model petsSharp.Pages.indexAnimaisModel
@{
	Layout = null;
}


<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Animais</title>
    <link href="~/css/styleAnimais.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="styleAnimais.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body style="background-color: #151A30;">
    <header>
      <div id="cabecalho">
        <img id="profileicon" src="~/img/Imagens_animal/profileicon.png">
        <a asp-page="/index" asp-area=""  style="color: red;">Sair</a>
      </div>
    </header>
    <main>
      <div id="menu">
    <a class="textoDashboard" asp-page="/dashboard" asp-area="" style="color: white;">Dashboard</a>
        <img class="ImagemDashboard" src="~/img/Imagens_animal/dashboard.png">
        <a class="textoEstoque" asp-page="/estoque" asp-area="" style="color: white">Estoque</a>
        <img class="ImagemEstoque" src="~/img/Imagens_animal/estoque.png">
        <a class="textoVendas" asp-page="/indexVendas" asp-area="" style="color: white">Vendas</a>
        <img class="ImagemVendas" src="~/img/Imagens_animal/sales.png">
        <div class="selecionado">
            <a class="textoAnimais" asp-page="/indexAnimais" asp-area="" style="color: #004BE3;">Animais</a>
            <img class="ImagemAnimais" src="~/img/Imagens_animal/animais.png">
            <a class="textoCadastrarAnimais" asp-page="/cadastrarAnimal" asp-area="" style="color: white">Cadastrar animais</a>
        </div>
        <a class="textoBanhoetosa" asp-page="/indexBanhoETosa" asp-area="" style="color: white;">Banho e tosa</a>
        <img class="ImagemTesoura" src="~/img/Imagens_animal/tesoura.png">
      </div>
      <div class="quadradoCentral">
        <form asp-page-handler="Pesquisa" method="post" class="d-flex barraDePesquisa" role="search">
            <input asp-for="@Model.pesquisa" class="form-control text-white border-black" type="search" placeholder="" aria-label="Search" style="background-color: #212B46; width: 200px;">
            <button class="btn border-black" type="submit" style="background-color: #212B46; color: white;">Pesquisar</button>
          </form>
          <form class="d-flex barraDeExclusao" role="search">
            <input class="form-control text-white border-black" type="search" placeholder="" aria-label="Search" style="background-color: #212B46; width: 200px;">
            <button class="btn border-black" type="submit" style="background-color: red; color: white;">Excluir</button>
          </form>
			<div class="container mt-4">
				<div class="table-responsive">
					<table class="table table-striped table-dark dataTable" id="tabelaProdutos">
						<thead>
							<tr>
								<th scope="col">Codigo</th>
								<th scope="col">Especie</th>
								<th scope="col">Descricao</th>
								<th scope="col">Valor</th>
							</tr>
						</thead>
						<tbody>
							@foreach (Dictionary<string, string> dicionario in Model.list_animais)
							{
								<tr>
									<td>@dicionario["codigo"]</td>
									<td>@dicionario["especie"]</td>
									<td>@dicionario["descricao"]</td>
									<td>R$ @dicionario["valor"]</td>
								</tr>
							}
						</tbody>
					</table>
				</div>
			</div>

		</div>
	</main>
	<script>
		$(document).ready(function () {
			$('#tabelaProdutos').DataTable({
				"paging": true,
				"pageLength": 10,
				"lengthMenu": [10, 20, 50],
				"info": false,
				"searching": false,
				"language": {
					"emptyTable": "Sem dados disponíveis",
					"info": "Mostrando _START_ até _END_ de _TOTAL_ registros",
					"infoEmpty": "Mostrando 0 até 0 de 0 registros",
					"infoFiltered": "(filtrado de _MAX_ registros no total)",
					"lengthMenu": "Mostrar _MENU_ registros por página",
					"zeroRecords": "Nenhum registro encontrado",
					"paginate": {
						"first": "Primeiro",
						"previous": "Anterior",
						"next": "Próximo",
						"last": "Último"
					}
				},
				"drawCallback": function (settings) {
					$('.custom-length-text').css('color', 'white');
					$('.custom-paginate-text').find('label').css('color', 'white');
				}

			});

			$('.dataTables_length').find('label').css('color', 'white');
			$('.dataTables_paginate').find('label').css('color', 'white !important');

		});
	</script>
  </body>
</html>